package view;

import dao.VendaDao;
import exceptions.BancoException;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Venda;

public class ListagemVenda extends javax.swing.JInternalFrame {

    CadastroVendas cadastro;
    VendaDao dao = new VendaDao();
    /**
     * Creates new form ListagemMetas
     */
    public ListagemVenda(CadastroVendas cadastro) {
        this.cadastro = cadastro;
        initComponents();
        criaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMetas = new javax.swing.JTable();
        jButtonSelecionar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Metas");

        jTableMetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIÇÃO", "VALOR", "INÍCIO", "FINAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMetas);

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSelecionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        try{
            if(jTableMetas.getSelectedRow() <0){
                throw new IllegalArgumentException("Nenhum registro selecionado!");
            }
            
            Venda v = getLinha();
            
            cadastro.preencheVenda(v);
            
            this.dispose();
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMetas;
    // End of variables declaration//GEN-END:variables

    private void criaTabela() {
        
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        
        VendaDao dao = new VendaDao();
        
        jTableMetas.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("DESCRIÇÂO");
        modelo.addColumn("CLIENTE");
//        modelo.addColumn("VALOR");
        jTableMetas.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableMetas.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableMetas.getColumnModel().getColumn(2).setPreferredWidth(200);
//        jTableMetas.getColumnModel().getColumn(4).setPreferredWidth(200);
        
        try {
            for (Venda venda : dao.getAll()) {
                modelo.addRow(new Object[]{venda.getId(), venda.getDescricao(), venda.getNomeCliente()});
            }
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
   
    
    public Venda getLinha() throws BancoException {
       
        int selecionada = jTableMetas.getSelectedRow();
        
        Venda v = new Venda();

        Object obj = jTableMetas.getValueAt(selecionada, 0);
        int codigo = (int) obj;

        v = dao.getVenda(codigo);

        return v;

    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
}
