/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ComissaoDao;
import exceptions.BancoException;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Comissao;

/**
 *
 * @author Leonardo
 */
public class ListagemComissao extends javax.swing.JInternalFrame {

    CadastroComissao cadastroComissao;
    CadastroVendedor cadastroVendedor;
    String view;
    /**
     * Creates new form ListagemMetas
     */
    public ListagemComissao(CadastroComissao cadastroComissao) {
        this.cadastroComissao = cadastroComissao;
        view="CADASTROCOMISSAO";
        initComponents();
        criaTabela();
    }
    
    public ListagemComissao(CadastroVendedor cadastroVendedor) {
        this.cadastroVendedor = cadastroVendedor;
        view="CADASTROVENDEDOR";
        initComponents();
        criaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMetas = new javax.swing.JTable();
        jButtonSelecionar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Comissões");

        jTableMetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIÇÃO", "VALOR", "INÍCIO", "FINAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMetas);

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSelecionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        try{
            if(jTableMetas.getSelectedRow() <0){
                throw new IllegalArgumentException("Nenhum registro selecionado!");
            }
            
            switch(view) {
                case "CADASTROCOMISSAO":   
                    cadastroComissao.preencheComissao(getLinha());
                    break; 
                    
                case "CADASTROVENDEDOR":
                    cadastroVendedor.preencheComissao(getLinha());
                    break;
            }
            
            this.dispose();
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMetas;
    // End of variables declaration//GEN-END:variables

    private void criaTabela() {
        
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        
        ComissaoDao dao = new ComissaoDao();
        
        jTableMetas.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("VALOR");
        modelo.addColumn("INÍCIO");
        modelo.addColumn("FINAL");
        
        jTableMetas.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableMetas.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableMetas.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableMetas.getColumnModel().getColumn(3).setPreferredWidth(200);
        
        try {
            for (Comissao comissao : dao.getAll()) {
                modelo.addRow(new Object[]{comissao.getId(), comissao.getValor(), comissao.getDataInicio(), comissao.getDataFinal()});
            }
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
   
    
    public Comissao getLinha() throws BancoException {
       
        int selecionada = jTableMetas.getSelectedRow();
        
        Comissao comissao = new Comissao();
        ComissaoDao dao = new ComissaoDao();

        Object obj = jTableMetas.getValueAt(selecionada, 0);
        int codigo = (int) obj;

        comissao = dao.getComissao(codigo);

        return comissao;

    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
}
