package view;

import dao.TransportadorDao;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Transportador;
import exceptions.BancoException;
public class ListagemTransportador extends javax.swing.JInternalFrame {
    
    CadastroTransportador cadastroTransportador;
    
    public ListagemTransportador(CadastroTransportador cadastro) {
        this.cadastroTransportador = cadastro;
        initComponents();
        criaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSelecionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTransportadores = new javax.swing.JTable();

        setClosable(true);
        setTitle("Lista de Transportadores");

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jTableTransportadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "PLACA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTransportadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 341, Short.MAX_VALUE)
                        .addComponent(jButtonSelecionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSelecionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        // TODO add your handling code here:
        try {
            cadastroTransportador.preencheTransportador(getLinha());
        } catch (BancoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        this.dispose();
    }//GEN-LAST:event_jButtonSelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTransportadores;
    // End of variables declaration//GEN-END:variables

    private void criaTabela() {
        
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        
        TransportadorDao dao = new TransportadorDao();
        
        jTableTransportadores.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("PLACA");
        
        
        jTableTransportadores.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableTransportadores.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableTransportadores.getColumnModel().getColumn(2).setPreferredWidth(200);
        
        try {
            for (Transportador t : dao.getAll()) {
                modelo.addRow(new Object[]{t.getId(), t.getNome(), t.getPlaca()});
            }
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
     
     public Transportador getLinha() throws BancoException {
       
        int selecionada = jTableTransportadores.getSelectedRow();
        
        Transportador t = new Transportador();
        TransportadorDao dao = new TransportadorDao();

        if (selecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um transportador!");
        }

        Object obj = jTableTransportadores.getValueAt(selecionada, 0);
        int codigo = (int) obj;

        t = dao.getTransportador(codigo);

        return t;

    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

}
