/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MunicipioDao;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Municipio;
import exceptions.BancoException;


public class ListagemMunicipio extends javax.swing.JInternalFrame {
    String view;
    CadastroMunicipio cadastroMunicipio;
    CadastroPessoa cadastroPessoa;
            
    public ListagemMunicipio(CadastroMunicipio cadastroMunicipio) {
        view="CADASTROMUNICIPIO";
        this.cadastroMunicipio = cadastroMunicipio;
        initComponents();
        criaTabela();
    }
    
    public ListagemMunicipio(CadastroPessoa cadastroPessoa) {
        view="CADASTROPESSOA";
        this.cadastroPessoa = cadastroPessoa;
        initComponents();
        criaTabela();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMunicipios = new javax.swing.JTable();
        jButtonSelecionar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Municípios");

        jTableMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "IBGE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMunicipios);

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSelecionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        try{
            if(jTableMunicipios.getSelectedRow() <0){
                throw new IllegalArgumentException("Nenhum registro selecionado!");
            }
            switch(view){
                case "CADASTROMUNICIPIO":
                    cadastroMunicipio.preencheMunicipio(getLinha());
                    break;
                case "CADASTROPESSOA":
                    cadastroPessoa.preencheMunicipio(getLinha());
                     break;
            }
            
            this.dispose();
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMunicipios;
    // End of variables declaration//GEN-END:variables
    
    private void criaTabela() {
        
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        
        MunicipioDao dao = new MunicipioDao();
        
        jTableMunicipios.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("NOME");
        modelo.addColumn("IBGE");
        
        jTableMunicipios.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableMunicipios.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableMunicipios.getColumnModel().getColumn(2).setPreferredWidth(200);
        
        try {
            for (Municipio municipio : dao.getAll()) {
                modelo.addRow(new Object[]{municipio.getId(), municipio.getNome(), municipio.getIbge()});
            }
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
     
     public Municipio getLinha() throws BancoException {
       
        int selecionada = jTableMunicipios.getSelectedRow();
        
        Municipio municipio = new Municipio();
        MunicipioDao dao = new MunicipioDao();

        if (selecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um municipio!");
        }

        Object obj = jTableMunicipios.getValueAt(selecionada, 0);
        int codigo = (int) obj;

        municipio = dao.getMunicipio(codigo);

        return municipio;

    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

}
